# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - echo "{{.VERSION}}"
    silent: true

  format:
    cmds:
      - rye run ruff . --fix --exit-zero
      - rye run black .
      - rye run isort .
      - rye run mypy .