# https://taskfile.dev

version: "3"

tasks:
  default:
    cmds:
      - echo "{{.VERSION}}"
    silent: true

  format:
    cmds:
      - ruff . --fix --exit-zero
      - black .
      - isort .
      - mypy .

  dbrevision:
    cmds:
      - alembic revision --autogenerate

  dbhead:
    cmds:
      - alembic upgrade head
