"""empty message

Revision ID: 2c6be6d4f08a
Revises:
Create Date: 2023-11-05 14:46:02.055830

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "2c6be6d4f08a"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sensor",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("time", sa.DATETIME(), nullable=False),
        sa.Column("external_temperature", sa.Float(), nullable=False),
        sa.Column("external_humidity", sa.Float(), nullable=False),
        sa.Column("internal_temperature", sa.Float(), nullable=False),
        sa.Column("internal_humidity", sa.Float(), nullable=False),
        sa.Column("drying", sa.Boolean(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["session.session_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "session",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("shoe_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["shoe_id"],
            ["shoe.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id"),
    )
    op.create_table(
        "shoe",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
