"""empty message

Revision ID: 0ea1059c8f7c
Revises: 8bd32b7bb552
Create Date: 2023-11-18 21:52:58.786979

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "0ea1059c8f7c"
down_revision: Union[str, None] = "8bd32b7bb552"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("session", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column("session", sa.Column("weather_code", sa.Integer(), nullable=False))
    op.add_column("user", sa.Column("ido_longitude", sa.Float(), nullable=False))
    op.add_column("user", sa.Column("keido_latitude", sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "keido_latitude")
    op.drop_column("user", "ido_longitude")
    op.drop_column("session", "weather_code")
    op.drop_column("session", "created_at")
    # ### end Alembic commands ###
