"""empty message

Revision ID: 861f09faff9c
Revises: 41fa0bc1e4c2
Create Date: 2023-11-08 21:52:04.047229

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "861f09faff9c"
down_revision: Union[str, None] = "41fa0bc1e4c2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("session", sa.Column("device_id", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("session", "device_id")
    # ### end Alembic commands ###
