"""empty message

Revision ID: 1ac6249e550f
Revises:
Create Date: 2023-11-05 11:30:39.696969

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "1ac6249e550f"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shoe",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("last_used", sa.DATETIME(), nullable=False),
        sa.Column("shoe_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["shoe_id"],
            ["shoe.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id"),
    )
    op.create_table(
        "sensors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("devied_id", sa.String(), nullable=True),
        sa.Column("time", sa.DATETIME(), nullable=False),
        sa.Column("external_temperature", sa.Float(), nullable=False),
        sa.Column("external_humidity", sa.Float(), nullable=False),
        sa.Column("internal_temperature", sa.Float(), nullable=False),
        sa.Column("internal_humidity", sa.Float(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.session_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
