name: Python formatter
on:
  push:

jobs:
  format:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependency
        run: |
          pip install -r requirements.lock -r requirements-dev.lock
      - name: Check Type
        run: |
          mypy .
      - name: Lint
        run: |
          ruff .
      - name: Check Format
        run: |
          black --check .
          isort --check .
